-- supabase_schema.sql
-- Run this in your Supabase SQL Editor

-- 1. Create Tables

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  username TEXT UNIQUE,
  password TEXT,
  role TEXT,
  "empId" TEXT,
  process TEXT,
  designation TEXT,
  "isActive" SMALLINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "artistName" TEXT,
  "empId" TEXT,
  "adId" TEXT,
  version TEXT,
  database TEXT,
  udac TEXT,
  status TEXT DEFAULT 'Submitted',
  "submittedAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS queries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  database TEXT,
  "adId" TEXT,
  version TEXT,
  "acquiredDate" DATE,
  udac TEXT,
  "queriedBy" TEXT,
  "queriedDate" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  "daysToExtract" INTEGER,
  "queryCode" TEXT,
  "queryCategory" TEXT,
  "queryDetails" TEXT,
  status TEXT DEFAULT 'Pending',
  validated TEXT DEFAULT 'Pending',
  raised TEXT DEFAULT 'Pending',
  remarks TEXT,
  "supervisorId" BIGINT,
  "approvedBy" TEXT,
  "resolvedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adId" TEXT,
  "artistName" TEXT,
  "prooferName" TEXT,
  "errorCategory" TEXT,
  "errorRemarks" TEXT,
  "checklistStatus" TEXT,
  "auditedAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS appeals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "errorId" BIGINT,
  "adId" TEXT,
  "artistName" TEXT,
  "appealDesc" TEXT,
  status TEXT DEFAULT 'Pending',
  "appealedAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  "resolutionNote" TEXT
);

CREATE TABLE IF NOT EXISTS config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT,
  value TEXT,
  UNIQUE(type, value)
);

-- 2. Initial Seed Data

-- Admin User
INSERT INTO users (name, username, password, role, "empId", "isActive") 
VALUES ('System Admin', 'admin', 'admin123', 'Admin', 'ADM001', 1)
ON CONFLICT (username) DO NOTHING;

-- Config Values
INSERT INTO config (type, value) VALUES 
('Version', 'New'), ('Version', 'Revision'), ('Version', 'Correction'),
('Database', 'Print'), ('Database', 'Digital'), ('Database', 'Social'),
('UDAC', 'HP'), ('UDAC', 'FP'), ('UDAC', 'QP'),
('Checklist', 'Logo verified'), ('Checklist', 'Spelling checked'), 
('Checklist', 'Dimensions correct'), ('Checklist', 'Color profile set'),
('ErrorCategory', 'No Error'), ('ErrorCategory', 'Missing Space/Bullet'), 
('ErrorCategory', 'Distorted Logo/Image'), ('ErrorCategory', 'Wrong Spelling'), 
('ErrorCategory', 'Not Following C/S Instructions'), ('ErrorCategory', 'Wrong Border'), 
('ErrorCategory', 'GRP Referenced Ad'), ('ErrorCategory', 'Copy Sheet Required'), 
('ErrorCategory', 'Art Work Problem'),
('Settings', 'Artist Dropdown Enabled')
ON CONFLICT (type, value) DO NOTHING;

-- 3. Stored Procedure for Dashboard Stats
CREATE OR REPLACE FUNCTION get_dashboard_stats(start_date text, end_date text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_start_timestamp timestamptz;
  v_end_timestamp timestamptz;
  v_total_submissions int;
  v_submissions_today int;
  v_total_audits int;
  v_audits_today int;
  v_total_errors int;
  v_pending_appeals int;
  v_approved_appeals int;
  v_rejected_appeals int;
  v_pending_queries int;
  v_resolved_queries int;
  v_error_breakdown json;
  v_users_by_role json;
  v_history json;
  result json;
BEGIN
  -- Parse dates explicitly as AT TIME ZONE 'UTC'
  v_start_timestamp := start_date::timestamptz;
  v_end_timestamp := end_date::timestamptz;

  SELECT count(*) INTO v_total_submissions 
  FROM submissions 
  WHERE "submittedAt" >= v_start_timestamp AND "submittedAt" < v_end_timestamp;

  SELECT count(*) INTO v_submissions_today 
  FROM submissions 
  WHERE date("submittedAt" AT TIME ZONE 'UTC') = current_date;

  SELECT count(*) INTO v_total_audits 
  FROM audits 
  WHERE "auditedAt" >= v_start_timestamp AND "auditedAt" < v_end_timestamp;

  SELECT count(*) INTO v_audits_today 
  FROM audits 
  WHERE date("auditedAt" AT TIME ZONE 'UTC') = current_date;

  SELECT count(*) INTO v_total_errors 
  FROM audits 
  WHERE "errorCategory" != 'No Error' AND "auditedAt" >= v_start_timestamp AND "auditedAt" < v_end_timestamp;

  SELECT count(*) INTO v_pending_appeals FROM appeals WHERE status = 'Pending' AND "appealedAt" >= v_start_timestamp AND "appealedAt" < v_end_timestamp;
  SELECT count(*) INTO v_approved_appeals FROM appeals WHERE status = 'Appeal Accepted' AND "appealedAt" >= v_start_timestamp AND "appealedAt" < v_end_timestamp;
  SELECT count(*) INTO v_rejected_appeals FROM appeals WHERE status = 'Appeal Rejected' AND "appealedAt" >= v_start_timestamp AND "appealedAt" < v_end_timestamp;
  
  SELECT count(*) INTO v_pending_queries FROM queries WHERE status = 'Pending' AND "queriedDate" >= v_start_timestamp AND "queriedDate" < v_end_timestamp;
  SELECT count(*) INTO v_resolved_queries FROM queries WHERE status = 'Resolved' AND "queriedDate" >= v_start_timestamp AND "queriedDate" < v_end_timestamp;

  SELECT json_object_agg("errorCategory", count) INTO v_error_breakdown 
  FROM (
    SELECT "errorCategory", count(*) as count 
    FROM audits 
    WHERE "errorCategory" != 'No Error' AND "auditedAt" >= v_start_timestamp AND "auditedAt" < v_end_timestamp 
    GROUP BY "errorCategory"
  ) t;

  SELECT json_object_agg(role, count) INTO v_users_by_role 
  FROM (
    SELECT role, count(*) as count 
    FROM users 
    WHERE "isActive" = 1 
    GROUP BY role
  ) t;

  SELECT json_agg(row_to_json(h)) INTO v_history
  FROM (
    WITH RECURSIVE dates AS (
       SELECT v_start_timestamp::date as date
       UNION ALL
       SELECT (date + interval '1 day')::date
       FROM dates
       WHERE date < (v_end_timestamp::date - interval '1 day')::date
    )
    SELECT 
      d.date,
      (SELECT count(*) FROM submissions s WHERE date(s."submittedAt" AT TIME ZONE 'UTC') = d.date) as submissions,
      (SELECT count(*) FROM audits a WHERE date(a."auditedAt" AT TIME ZONE 'UTC') = d.date) as audits,
      (SELECT count(*) FROM audits a WHERE date(a."auditedAt" AT TIME ZONE 'UTC') = d.date AND a."errorCategory" != 'No Error') as errors
    FROM dates d
  ) h;

  result = json_build_object(
    'totalSubmissions', coalesce(v_total_submissions, 0),
    'submissionsToday', coalesce(v_submissions_today, 0),
    'totalAudits', coalesce(v_total_audits, 0),
    'auditsToday', coalesce(v_audits_today, 0),
    'totalErrors', coalesce(v_total_errors, 0),
    'appeals', json_build_object('pending', coalesce(v_pending_appeals, 0), 'approved', coalesce(v_approved_appeals, 0), 'rejected', coalesce(v_rejected_appeals, 0)),
    'queries', json_build_object('pending', coalesce(v_pending_queries, 0), 'resolved', coalesce(v_resolved_queries, 0)),
    'errorBreakdown', coalesce(v_error_breakdown, '{}'::json),
    'usersByRole', coalesce(v_users_by_role, '{}'::json),
    'history', coalesce(v_history, '[]'::json)
  );

  RETURN result;
END;
$$;
